version: "3.8"
services:
  napcat:
    container_name: napcat
    environment:
      - TZ=Asia/Shanghai
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID} # 让 NapCat 获取当前用户 GID,UID，防止权限问题
    ports:
      - 6099:6099
    restart: unless-stopped
    volumes:
      - /vol1/napCatData/QQ:/app/.config/QQ
      - /vol1/napCatData/config:/app/napcat/config
      - /vol1/LuwBotData/data:/MaiMBot/data #麦麦的图片等要给napcat不然发送图片会有问题
    image: mlikiowa/napcat-docker:latest
    networks:
      - luwbot
  luwbot:
    build: .
    container_name: luwbot
    ports:
      - "6810:8080"
    volumes:
      - /vol1/LuwBotData/config:/MaiMBot/config
      - /vol1/LuwBotData/data:/MaiMBot/data
      - /vol1/LuwBotData/.env.prod:/MaiMBot/.env.prod
      - /vol1/napCatData/config:/MaiMBot/napcat
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - mongodb
    networks:
      - luwbot
  mongodb:
    container_name: mongodb
    environment:
      - TZ=Asia/Shanghai
      # - MONGO_INITDB_ROOT_USERNAME=your_username
      # - MONGO_INITDB_ROOT_PASSWORD=your_password
    ports:
      - "7017:27017"
    restart: always
    volumes:
      - /vol1/LuwBotData/mongodb/db:/data/db
      - /vol1/LuwBotData/mongodb/configdb:/data/configdb
    image: mongo:latest
    networks:
      - luwbot

networks:
  luwbot:
    driver: bridge